# Mobile App Dockerfile
# It is recommended to use the web application (apps/web) Dockerfile for the project.
# For the mobile application, we are working to create a Dockerfile that can be used for development and testing purposes.
