"""30 Authentic Indian Handicraft Products across 6 GI Craft Categories.

Each item includes:
- Category & GI Cluster
- Detailed Artisan Profile & Heritage Story
- Complete voice-cataloging fields (material, cost, hours, technique, motifs, etc.)
- 4-tier pricing model with provenance
- Bilingual copy (English & Hindi)
- Search and filtering tags
- Cryptographic HMAC-SHA256 signature and QR link
"""

from __future__ import annotations

from typing import Any

from kalasetu_api.config import get_settings
from kalasetu_api.engines.pricing import compute_prices
from kalasetu_api.engines.signing import compute_listing_signature

CRAFT_CATEGORIES = [
    "Handloom & Textiles",
    "Metal Craft & Dhokra",
    "Pottery & Ceramics",
    "Woodcraft & Lacquerware",
    "Leather & Footwear",
    "Stone Craft & Jewelry",
]

RAW_CATALOG_DATA: list[dict[str, Any]] = [
    # -------------------------------------------------------------------------
    # 1. Handloom & Textiles (5 items)
    # -------------------------------------------------------------------------
    {
        "id": "banarasi-katan-silk-saree",
        "category": "Handloom & Textiles",
        "craft": "handloom",
        "cluster": "varanasi",
        "cluster_name": "Varanasi, Uttar Pradesh",
        "artisan": {
            "name": "Ustad Bashir Ahmed",
            "phone": "+919839124501",
            "uid": "artisan-bashir-varanasi",
            "experience_years": 34,
            "pehchan_id": "UP-VAR-WEA-4021",
        },
        "title": "Banarasi Katan Silk Handloom Saree",
        "title_en": "Pure Katan Silk Banarasi Saree with Zari Kadwa Floral Jaal",
        "title_hi": "शुद्ध कतान रेशम बनारसी साड़ी - जरी कड़वा काम",
        "description": "Handwoven on a traditional pit loom over 36 painstaking hours, this masterpiece features pure mulberry silk (Katan) with intricate Kadwa gold-zari weaving. Traditional floral jaal motifs cascade across the drape, ending in an opulent pallu.",
        "desc_en": "Woven with Grade-A mulberry Katan silk warp and weft, interlaced with tested gold zari in the intricate Kadwa technique where each motif is engraved individually without float threads.",
        "desc_hi": "पारंपरिक गड्ढा करघे पर 36 घंटों की अथक मेहनत से तैयार, शुद्ध शहतूत कतान रेशम और शुद्ध सोने की जरी का बारीक कड़वा काम। शाही पल्लू और पारम्परिक बूटा इस साड़ी को अद्वितीय बनाते हैं।",
        "photo_url": "https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=900&q=80",
        "fields": {
            "craft": "handloom",
            "sub_craft": "saree",
            "material": "Pure Mulberry Silk (Katan) & Gold Zari",
            "material_cost_inr": 3400,
            "material_source": "Bunkar Sahakari Samiti Varanasi",
            "technique": "Handloom Kadwa Interlock Weave",
            "hours": 36,
            "wage_inr_per_hour": 85,
            "effort": "skilled",
            "gi": "yes",
            "motif": "Kalka (Paisley) & Phool Jaal",
            "colour": ["Crimson Red", "Antique Gold"],
            "dimensions": "5.5m Saree + 0.8m Blouse Piece",
            "weight_g": 850,
            "care_instructions": "Dry clean only. Store wrapped in pure muslin cloth.",
            "authenticity_mark": "Silk Mark & GI Tag Certified",
        },
        "price_hint": 9200,
        "tags": [
            "handloom",
            "silk",
            "saree",
            "varanasi",
            "gi-tag",
            "wedding",
            "zari",
            "kadwa",
            "textiles",
            "katan",
        ],
    },
    {
        "id": "chanderi-silk-cotton-dupatta",
        "category": "Handloom & Textiles",
        "craft": "handloom",
        "cluster": "chanderi",
        "cluster_name": "Chanderi, Madhya Pradesh",
        "artisan": {
            "name": "Meenakshi Bai Koli",
            "phone": "+919754812302",
            "uid": "artisan-meenakshi-chanderi",
            "experience_years": 22,
            "pehchan_id": "MP-CHA-WEA-1104",
        },
        "title": "Chanderi Silk Cotton Handwoven Dupatta",
        "title_en": "Sheer Chanderi Silk-Cotton Dupatta with Gold Muniya Border",
        "title_hi": "चंदेरी रेशम-सूती दुपट्टा - मुनिया जरी किनारी",
        "description": "Celebrated for its feather-light sheer texture and lustrous gossamer feel, this Chanderi dupatta is woven with 300-count degummed silk warp and fine mallow cotton weft, accented with traditional parrot (Muniya) gold borders.",
        "desc_en": "Handcrafted on traditional throw-shuttle pit looms using fine silk and unbleached cotton threads. Features delicate gold zari buttis sprinkled across an ivory base with emerald selvedge.",
        "desc_hi": "पारंपरिक हाथकरघे पर बुना गया बेहद हल्का और पारदर्शी चंदेरी दुपट्टा। महीन रेशम और सूती धागों के संगम पर सुनहरी मुनिया किनारी और छोटी-छोटी बूटियाँ।",
        "photo_url": "https://images.unsplash.com/photo-1607522370275-f14206abe5d3?auto=format&fit=crop&w=900&q=80",
        "fields": {
            "craft": "handloom",
            "sub_craft": "dupatta",
            "material": "Chanderi Silk Cotton Blend (70:30)",
            "material_cost_inr": 950,
            "material_source": "Chanderi Weaver Guild",
            "technique": "Extra-weft Throw-shuttle Weaving",
            "hours": 14,
            "wage_inr_per_hour": 85,
            "effort": "skilled",
            "gi": "yes",
            "motif": "Ashrafi & Muniya (Parrot)",
            "colour": ["Ivory", "Emerald Green", "Gold"],
            "dimensions": "2.5m x 0.9m",
            "weight_g": 180,
            "care_instructions": "Gentle hand wash with mild reetha liquid or dry clean.",
            "authenticity_mark": "Chanderi GI Certified",
        },
        "price_hint": 3100,
        "tags": [
            "handloom",
            "dupatta",
            "chanderi",
            "silk-cotton",
            "gi-tag",
            "festive",
            "textiles",
            "sheer",
        ],
    },
    {
        "id": "pashmina-sozni-embroidered-shawl",
        "category": "Handloom & Textiles",
        "craft": "handloom",
        "cluster": "kashmir",
        "cluster_name": "Srinagar, Jammu & Kashmir",
        "artisan": {
            "name": "Ghulam Hassan Mir",
            "phone": "+919419056703",
            "uid": "artisan-ghulam-kashmir",
            "experience_years": 40,
            "pehchan_id": "JK-SRI-SHA-8921",
        },
        "title": "Kashmiri Hand-Spun Pashmina Sozni Shawl",
        "title_en": "Authentic Changthangi Pashmina Shawl with Fine Needle Sozni Embroidery",
        "title_hi": "कश्मीरी हाथ-कता पश्मीना शॉल - सोज़नी सुई कशीदाकारी",
        "description": "Crafted from the soft underfleece of Ladakh's high-altitude Capra Hircus mountain goats (Changthangi), hand-spun on wooden charkhas and ornamented with microscopic Sozni needlework representing the Chinar leaf.",
        "desc_en": "100% pure Grade-A Cashmere Pashmina spun and woven in Srinagar. The Sozni needle embroidery is executed with single-filament silk thread requiring weeks of concentrated precision.",
        "desc_hi": "लद्दाख के चांगथांगी बकरों के प्राकृतिक ऊन से हाथ द्वारा कता और बुना गया पश्मीना शॉल। बारीक रेशमी धागों से चिनार पत्ती की सोज़नी सुई-कशीदाकारी।",
        "photo_url": "https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=900&q=80",
        "fields": {
            "craft": "handloom",
            "sub_craft": "shawl",
            "material": "100% Changthangi Cashmere Pashmina Wool",
            "material_cost_inr": 4800,
            "material_source": "Ladakh Pashmina Cooperative",
            "technique": "Handspun Yarn & Sozni Needlework Embroidery",
            "hours": 48,
            "wage_inr_per_hour": 110,
            "effort": "skilled",
            "gi": "yes",
            "motif": "Chinar Leaf & Badam Paisley",
            "colour": ["Natural Oatmeal", "Walnut Brown", "Crimson"],
            "dimensions": "2.0m x 1.0m",
            "weight_g": 220,
            "care_instructions": "Strictly dry clean. Preserve with neem leaves in cedar chests.",
            "authenticity_mark": "Kashmir Pashmina GI Tagged",
        },
        "price_hint": 14500,
        "tags": [
            "pashmina",
            "cashmere",
            "shawl",
            "kashmir",
            "gi-tag",
            "sozni",
            "winter",
            "textiles",
            "luxury",
        ],
    },
    {
        "id": "pochampally-ikat-cotton-saree",
        "category": "Handloom & Textiles",
        "craft": "handloom",
        "cluster": "pochampally",
        "cluster_name": "Pochampally, Telangana",
        "artisan": {
            "name": "Narsimha Chary",
            "phone": "+919848034504",
            "uid": "artisan-narsimha-pochampally",
            "experience_years": 28,
            "pehchan_id": "TS-POC-WEA-3312",
        },
        "title": "Pochampally Double Ikat Handwoven Cotton Saree",
        "title_en": "Geometric Double Ikat Cotton Saree with Natural Indigo Dyes",
        "title_hi": "पोचमपल्ली डबल इकत सूती साड़ी - प्राकृतिक नील रंग",
        "description": "Known as Pagdu Bandhu in Telangana, this double ikat saree demands mathematical precision where both warp and weft yarns are tied and dyed in geometric matrices before weaving.",
        "desc_en": "100% combed cotton handloom saree featuring clean diamond ikat checks with natural plant indigo and madder root red pigments, complete with traditional temple selvedge border.",
        "desc_hi": "वारप और वेफ्ट दोनों धागों को नापकर बांधी जाने वाली जटिल डबल इकत तकनीक। प्राकृतिक नील और मजीठ रंगों से रंगा शुद्ध सूती हाथकरघा वस्त्र।",
        "photo_url": "https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=900&q=80",
        "fields": {
            "craft": "handloom",
            "sub_craft": "ikat",
            "material": "100% Combed Mercerized Cotton",
            "material_cost_inr": 1100,
            "material_source": "Bhoodan Pochampally Society",
            "technique": "Double Ikat Resist Dyeing & Pitloom Weave",
            "hours": 22,
            "wage_inr_per_hour": 85,
            "effort": "skilled",
            "gi": "yes",
            "motif": "Chowka (Diamond) & Temple Border",
            "colour": ["Deep Indigo", "Madder Red", "Ecru White"],
            "dimensions": "5.5m Saree + 0.8m Blouse",
            "weight_g": 580,
            "care_instructions": "First wash dry clean, subsequently mild cold hand wash.",
            "authenticity_mark": "Pochampally Ikat GI Certified",
        },
        "price_hint": 4600,
        "tags": [
            "handloom",
            "ikat",
            "pochampally",
            "cotton",
            "gi-tag",
            "natural-dye",
            "textiles",
            "geometric",
        ],
    },
    {
        "id": "kutch-kala-cotton-ajrakh-stole",
        "category": "Handloom & Textiles",
        "craft": "handloom",
        "cluster": "kutch",
        "cluster_name": "Bhuj, Kutch, Gujarat",
        "artisan": {
            "name": "Ismail Mohammed Khatri",
            "phone": "+919426912305",
            "uid": "artisan-ismail-kutch",
            "experience_years": 31,
            "pehchan_id": "GJ-BHU-AJR-7705",
        },
        "title": "Kutch Kala Cotton Hand-Block Ajrakh Stole",
        "title_en": "Rainfed Kala Cotton Stole with 16-Stage Natural Dye Ajrakh Print",
        "title_hi": "कच्छ काला कॉटन अजरख दुपट्टा - १६ चरणों की प्राकृतिक छपाई",
        "description": "Handspun from indigenous, rainfed, GMO-free organic Kala cotton of the arid Kutch desert, handprinted with wooden blocks through the sacred 16-step Ajrakh process using iron rust, indigo, and pomegranate peel.",
        "desc_en": "Pure organic Kala cotton woven on semi-automatic looms and printed in Dhamadka with mineral mordants and vegetable extracts, resulting in rich deep blue and madder earthy shades.",
        "desc_hi": "कच्छ की मिट्टी में बिना सिंचाई उगने वाली जैविक काला कपास। १६ चरणों की प्राचीन अजरख ब्लॉक प्रिंटिंग, जिसमें लोहे के जंग और अनार के छिलके का उपयोग होता है।",
        "photo_url": "https://images.unsplash.com/photo-1598033129183-c4f50c736f10?auto=format&fit=crop&w=900&q=80",
        "fields": {
            "craft": "handloom",
            "sub_craft": "ajrakh",
            "material": "100% Organic Desi Kala Cotton",
            "material_cost_inr": 780,
            "material_source": "Khamir Artisan Trust Kutch",
            "technique": "Hand Block Printing & Mud Resist (Ajrakh)",
            "hours": 16,
            "wage_inr_per_hour": 85,
            "effort": "skilled",
            "gi": "yes",
            "motif": "Star & Trefoil Islamic Geometry",
            "colour": ["Midnight Indigo", "Earthy Rust", "Mustard Yellow"],
            "dimensions": "2.1m x 0.65m",
            "weight_g": 240,
            "care_instructions": "Cold wash separately inside out with plant-based detergent.",
            "authenticity_mark": "Craftmark & Ajrakh Heritage Certified",
        },
        "price_hint": 2800,
        "tags": [
            "handloom",
            "kala-cotton",
            "ajrakh",
            "block-print",
            "kutch",
            "organic",
            "eco-friendly",
            "textiles",
        ],
    },

    # -------------------------------------------------------------------------
    # 2. Metal Craft & Dhokra (5 items)
    # -------------------------------------------------------------------------
    {
        "id": "moradabad-engraved-brass-urli",
        "category": "Metal Craft & Dhokra",
        "craft": "metalcraft",
        "cluster": "moradabad",
        "cluster_name": "Moradabad, Uttar Pradesh",
        "artisan": {
            "name": "Mohammad Rafeeq",
            "phone": "+919837012306",
            "uid": "artisan-rafeeq-moradabad",
            "experience_years": 25,
            "pehchan_id": "UP-MOR-MET-5542",
        },
        "title": "Moradabad Hand-Chiseled Brass Urli",
        "title_en": "Traditional Peetal Urli Bowl with Intricate Floral Naqshi Carving",
        "title_hi": "मुरादाबाद नक्काशीदार पीतल उरली - पारंपरिक दस्तकारी",
        "description": "Cast from heavy-gauge virgin brass in the Peetal Nagri of Moradabad, hand-lathe smoothed and meticulously engraved with fine chisels (Naqshi kaam) showcasing traditional floral vine and marigold patterns.",
        "desc_en": "Solid brass bowl perfect for floating candles and water flowers. Finished with a protective antique lacquer polish that resists oxidation while maintaining warm golden highlights.",
        "desc_hi": "मुरादाबाद के प्रसिद्ध पीतल उद्योग में पारंपरिक रेत-ढलाई द्वारा निर्मित उरली। कुशल कारीगर द्वारा हाथ की छेनी से बेल-बूटों की महीन नक्काशी।",
        "photo_url": "https://images.unsplash.com/photo-1615529182904-14819c35db37?auto=format&fit=crop&w=900&q=80",
        "fields": {
            "craft": "metalcraft",
            "sub_craft": "brass",
            "material": "Heavy Virgin Brass (70% Cu, 30% Zn)",
            "material_cost_inr": 1350,
            "material_source": "Moradabad Metal Traders Market",
            "technique": "Sand Casting & Manual Chisel Naqshi Engraving",
            "hours": 14,
            "wage_inr_per_hour": 95,
            "effort": "skilled",
            "gi": "yes",
            "motif": "Genda Phool (Marigold) & Creeper Vine",
            "colour": ["Burnished Gold", "Antique Patina"],
            "dimensions": "12 inch Diameter x 4 inch Height",
            "weight_g": 2400,
            "care_instructions": "Wipe with dry soft cloth. Clean with brasso or lemon-salt paste sparingly.",
            "authenticity_mark": "Moradabad Metal Craft GI Tagged",
        },
        "price_hint": 3900,
        "tags": [
            "metalcraft",
            "brass",
            "urli",
            "moradabad",
            "home-decor",
            "festive",
            "naqshi",
            "gi-tag",
        ],
    },
    {
        "id": "bastar-dhokra-tribal-musicians",
        "category": "Metal Craft & Dhokra",
        "craft": "metalcraft",
        "cluster": "bastar",
        "cluster_name": "Bastar, Chhattisgarh",
        "artisan": {
            "name": "Sukhram Ghadwa",
            "phone": "+919425267807",
            "uid": "artisan-sukhram-bastar",
            "experience_years": 30,
            "pehchan_id": "CG-BAS-DHO-0912",
        },
        "title": "Bastar Bell Metal Dhokra Tribal Musicians Set",
        "title_en": "Lost-Wax Bell Metal Sculpture Trio of Traditional Gond Musicians",
        "title_hi": "बस्तर ढोकरा कांस्य संगीतकार मूर्ति सेट - लुप्त-मोम शिल्प",
        "description": "Embodying a 4,000-year-old unbroken Indus Valley metallurgical tradition, this hollow bell metal sculpture depicts tribal folk musicians playing the Mandar drum, Tutari horn, and flute, shaped using beeswax cords.",
        "desc_en": "Individually handcrafted by Ghadwa tribal masters using the Cire Perdue lost-wax casting technique. Every piece is an irreplaceable original because the outer clay mold is smashed during extraction.",
        "desc_hi": "सिंधु घाटी सभ्यता की ४००० वर्ष पुरानी तकनीक। प्राकृतिक मोम के पतले तारों से बनी आकृति, जिसे मिट्टी के सांचे में ढालकर तोड़ा जाता है। प्रत्येक मूर्ति अपने आप में अनूठी है।",
        "photo_url": "https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=900&q=80",
        "fields": {
            "craft": "metalcraft",
            "sub_craft": "dhokra",
            "material": "Recycled Brass, Bell Metal Alloy, Beeswax, Clay",
            "material_cost_inr": 850,
            "material_source": "Bastar Village Scrap Metal Guild",
            "technique": "Cire Perdue (Lost-Wax Hollow Cast)",
            "hours": 20,
            "wage_inr_per_hour": 90,
            "effort": "skilled",
            "gi": "yes",
            "motif": "Gond Tribal Musician & Ritual Animals",
            "colour": ["Earthy Bronze", "Rustic Brass Gold"],
            "dimensions": "8 inch Height x 4 inch Base (Each)",
            "weight_g": 1650,
            "care_instructions": "Dust gently with dry nylon brush. Avoid acidic cleaners.",
            "authenticity_mark": "Bastar Dhokra GI Certified",
        },
        "price_hint": 3600,
        "tags": [
            "metalcraft",
            "dhokra",
            "tribal",
            "bastar",
            "lost-wax",
            "figurine",
            "folk-art",
            "gi-tag",
        ],
    },
    {
        "id": "kansa-ayurvedic-dinner-thali-set",
        "category": "Metal Craft & Dhokra",
        "craft": "metalcraft",
        "cluster": "sarthebari",
        "cluster_name": "Sarthebari, Barpeta, Assam",
        "artisan": {
            "name": "Bipul Roy",
            "phone": "+919435012308",
            "uid": "artisan-bipul-assam",
            "experience_years": 26,
            "pehchan_id": "AS-SAR-KAN-2208",
        },
        "title": "Sarthebari Pure Kansa Ayurvedic Dinner Set",
        "title_en": "Hand-Hammered Bell Metal Kansa Dinner Set (Thali, 2 Katoris, Glass, Spoon)",
        "title_hi": "असम सरथबारी शुद्ध कांसा थाली सेट - हाथ से हथौड़ा निर्मित",
        "description": "Known as the Queen of Metals in Ayurveda for balancing Vata, Pitta, and Kapha, this authentic Kansa set is cast in an exact 78% Copper and 22% Tin proportion and hand-hammered while red-hot.",
        "desc_en": "Comprises a 12-inch lip-edge thali, two deep bowls, a drinking glass, and dessert spoon. When tapped, it produces a clear resonant bell chime, proving the metallurgical purity of the bronze alloy.",
        "desc_hi": "आयुर्वेद में स्वास्थ्यवर्धक माना जाने वाला ७८% तांबा और २२% रांगा का शुद्ध कांसा। लाल गर्म धातु पर लोहारों के दल द्वारा हाथों से हथौड़े की चोट मारकर तैयार।",
        "photo_url": "https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?auto=format&fit=crop&w=900&q=80",
        "fields": {
            "craft": "metalcraft",
            "sub_craft": "kansa",
            "material": "Pure Bell Metal (78% Copper, 22% Tin)",
            "material_cost_inr": 2300,
            "material_source": "Assam Cooperative Bell Metal Society",
            "technique": "Red-Hot Hand Hammering (Pita Kaam) & Lathe Polishing",
            "hours": 16,
            "wage_inr_per_hour": 95,
            "effort": "skilled",
            "gi": "yes",
            "motif": "Concentric Hammered Rings (Chhapa)",
            "colour": ["Golden Bronze", "Mirror Polished Rim"],
            "dimensions": "Thali 12 inch Dia, Bowls 3.5 inch, Glass 250ml",
            "weight_g": 1950,
            "care_instructions": "Wash with ash/pitambari powder and sponge. Dry immediately to prevent spots.",
            "authenticity_mark": "Sarthebari Bell Metal GI Tagged",
        },
        "price_hint": 5800,
        "tags": [
            "metalcraft",
            "kansa",
            "bell-metal",
            "thali",
            "ayurveda",
            "kitchenware",
            "healthy-dining",
            "gi-tag",
        ],
    },
    {
        "id": "bidriware-silver-inlay-trinket-box",
        "category": "Metal Craft & Dhokra",
        "craft": "metalcraft",
        "cluster": "bidar",
        "cluster_name": "Bidar, Karnataka",
        "artisan": {
            "name": "Abdul Rauf Rashid",
            "phone": "+919880123409",
            "uid": "artisan-rauf-bidar",
            "experience_years": 33,
            "pehchan_id": "KA-BID-BID-4019",
        },
        "title": "Bidriware Silver-Inlaid Hexagonal Trinket Box",
        "title_en": "Hexagonal Zinc Box with 99.9% Pure Silver Wire Inlay (Tarkashi)",
        "title_hi": "बिदरीवेयर चांदी जड़ा षट्कोणीय आभूषण डिब्बा - तारकशी",
        "description": "Originating in 14th century Bahmani sultanate, Bidriware is crafted from a blackened zinc-copper alloy permanently patinated using aged soil excavated from the 500-year-old Bidar Fort, inlaid with pure silver wire.",
        "desc_en": "Features the Tarkashi wire technique where thin pure silver ribbons are driven into engraved cavities with a wooden mallet, polished flush, and boiled in sal ammoniac mud for stark jet-black contrast.",
        "desc_hi": "बीदर किले की ऐतिहासिक मिट्टी से रासायनिक रूप से काला किया गया जस्ता मिश्रधातु। उस पर शुद्ध चांदी के तारों को छेनी से जड़कर बनाई गई शाही तारकशी।",
        "photo_url": "https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=900&q=80",
        "fields": {
            "craft": "metalcraft",
            "sub_craft": "bidriware",
            "material": "Zinc (96%), Copper (4%), Pure Silver Inlay (99.9%)",
            "material_cost_inr": 1650,
            "material_source": "Bidar Artisans Society",
            "technique": "Casting, Chiseling, Silver Tarkashi & Fort Soil Oxidation",
            "hours": 24,
            "wage_inr_per_hour": 95,
            "effort": "skilled",
            "gi": "yes",
            "motif": "Mughal Floral Arabesque & Poppy Motif",
            "colour": ["Velvet Matte Black", "Shimmering Silver"],
            "dimensions": "4.5 inch Width x 3.5 inch Depth x 2.2 inch Height",
            "weight_g": 620,
            "care_instructions": "Rub gently with soft flannel dipped in coconut oil once a year.",
            "authenticity_mark": "Bidriware GI Certified",
        },
        "price_hint": 4900,
        "tags": [
            "metalcraft",
            "bidriware",
            "silver-inlay",
            "bidar",
            "tarkashi",
            "gi-tag",
            "luxury-craft",
        ],
    },
    {
        "id": "swamimalai-bronze-nataraja-statue",
        "category": "Metal Craft & Dhokra",
        "craft": "metalcraft",
        "cluster": "swamimalai",
        "cluster_name": "Swamimalai, Thanjavur, Tamil Nadu",
        "artisan": {
            "name": "Sthapati Devasenapathy",
            "phone": "+919443123410",
            "uid": "artisan-sthapati-swamimalai",
            "experience_years": 42,
            "pehchan_id": "TN-SWA-BRO-9901",
        },
        "title": "Swamimalai Panchaloha Bronze Nataraja Icon",
        "title_en": "Chola Heritage Lost-Wax Panchaloha Bronze Dancing Shiva Nataraja",
        "title_hi": "स्वामीमलाई पंचलोहा कांस्य नटराज मूर्ति - चोल मूर्तिकला",
        "description": "Hand-sculpted in compliance with ancient Shilpa Shastras canon by hereditary Sthapatis, this Cosmic Dancing Shiva captures perfect cosmic poise framed by the flaming Prabhavali arch.",
        "desc_en": "Cast in sacred Panchaloha (copper, brass, lead, silver, gold traces) utilizing Kaveri river silt for the mold. Each icon requires hand-wax modeling with Dammar resin and coconut oil.",
        "desc_hi": "शिल्प शास्त्र के प्राचीन नियमों के अनुसार हस्तनिर्मित चोल साम्राज्य की कांस्य मूर्ति। कावेरी नदी की मिट्टी से बना मोल्ड और पंचधातु का शुद्ध मिश्रण।",
        "photo_url": "https://images.unsplash.com/photo-1567446537708-ac4aa75c9c28?auto=format&fit=crop&w=900&q=80",
        "fields": {
            "craft": "metalcraft",
            "sub_craft": "bronze",
            "material": "Sacred Panchaloha Bronze Alloy (85% Cu, 13% Sn, 2% Zn/Ag)",
            "material_cost_inr": 3800,
            "material_source": "Kumbakonam Hereditary Foundry",
            "technique": "Agama Shastra Lost-Wax Hollow/Solid Cast & Chisel Work",
            "hours": 32,
            "wage_inr_per_hour": 110,
            "effort": "skilled",
            "gi": "yes",
            "motif": "Ananda Tandava & Flaming Tiruvasi",
            "colour": ["Temple Antique Bronze", "Warm Olive Patina"],
            "dimensions": "11 inch Height x 9.5 inch Width x 3.5 inch Base",
            "weight_g": 3200,
            "care_instructions": "Dust with dry cotton cloth. Do not use chemical polishes.",
            "authenticity_mark": "Swamimalai Bronze Icons GI Certified",
        },
        "price_hint": 10500,
        "tags": [
            "metalcraft",
            "bronze",
            "swamimalai",
            "nataraja",
            "panchaloha",
            "sculpture",
            "gi-tag",
            "temple-art",
        ],
    },

    # -------------------------------------------------------------------------
    # 3. Pottery & Ceramics (5 items)
    # -------------------------------------------------------------------------
    {
        "id": "khurja-ceramic-floral-planter",
        "category": "Pottery & Ceramics",
        "craft": "pottery",
        "cluster": "khurja",
        "cluster_name": "Khurja, Bulandshahr, Uttar Pradesh",
        "artisan": {
            "name": "Rameshwar Prajapati",
            "phone": "+919837190011",
            "uid": "artisan-rameshwar-khurja",
            "experience_years": 24,
            "pehchan_id": "UP-KHU-CER-1902",
        },
        "title": "Khurja Studio Pottery Hand-Glazed Planter",
        "title_en": "Stoneware Ceramic Planter with Hand-Painted Mughal Botanical Glaze",
        "title_hi": "खुरजा सिरेमिक फ्लोरल गमला - हस्त निर्मित मुगल ग्लेज",
        "description": "Crafted in India's premier Ceramic City, this durable stoneware planter is wheel-thrown, hand-painted with cobalt oxides by local women artisans, and high-fired at 1250°C in an eco-friendly gas shuttle kiln.",
        "desc_en": "Vitreous non-porous ceramic featuring hand-applied floral slip work inspired by Mughal miniature gardens. Fully frost-resistant and suitable for indoor or patio plant cultivation.",
        "desc_hi": "खुरजा के ऐतिहासिक कुम्हार घराने द्वारा चाक पर निर्मित। कोबाल्ट ऑक्साइड से हाथ से रंगा गया मुगलिया पुष्प डिजाइन, १२५० डिग्री सेल्सियस पर पकाया गया मजबूत सिरेमिक।",
        "photo_url": "https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&w=900&q=80",
        "fields": {
            "craft": "pottery",
            "sub_craft": "ceramics",
            "material": "Stoneware White Clay, Quartz, Feldspar, Lead-Free Glaze",
            "material_cost_inr": 360,
            "material_source": "Khurja Pottery Development Center",
            "technique": "Wheel Thrown, Brush Slip Painting & High-Fire Vitrification",
            "hours": 7,
            "wage_inr_per_hour": 80,
            "effort": "normal",
            "gi": "yes",
            "motif": "Mughal Iris & Persian Leaf Lattice",
            "colour": ["Cobalt Blue", "Cream White", "Moss Green"],
            "dimensions": "7.5 inch Dia x 6.8 inch Height (with drainage hole)",
            "weight_g": 1450,
            "care_instructions": "Rinse with tap water. Weatherproof and frost resistant.",
            "authenticity_mark": "Khurja Pottery GI Certified",
        },
        "price_hint": 1450,
        "tags": [
            "pottery",
            "khurja",
            "ceramic",
            "planter",
            "hand-painted",
            "home-decor",
            "gi-tag",
            "garden",
        ],
    },
    {
        "id": "jaipur-blue-pottery-decorative-plate",
        "category": "Pottery & Ceramics",
        "craft": "pottery",
        "cluster": "jaipur",
        "cluster_name": "Jaipur, Rajasthan",
        "artisan": {
            "name": "Giriraj Sharma",
            "phone": "+919829033412",
            "uid": "artisan-giriraj-jaipur",
            "experience_years": 29,
            "pehchan_id": "RJ-JAI-BLU-4411",
        },
        "title": "Jaipur Blue Pottery Wall Accent Plate",
        "title_en": "Clay-Free Quartz Blue Pottery Wall Hanging Platter with Persian Motifs",
        "title_hi": "जयपुर ब्लू पॉटरी सजावटी थाली - फ़ारसी फूल बूटियाँ",
        "description": "Unique worldwide because it uses no clay at all; this traditional Jaipur Blue Pottery is crafted from dough made of crushed quartz, Fuller's earth, raw soda, and natural resins, painted with copper and cobalt oxides.",
        "desc_en": "10-inch decorative platter fitted with an integrated wall-mounting bracket. Low-fired in wood kilns to achieve the characteristic glossy turquoise and ultramarine glaze that never fades.",
        "desc_hi": "बिना मिट्टी के विशुद्ध क्वार्ट्ज पत्थर के पाउडर, मुल्तानी मिट्टी और गोंद से निर्मित प्रसिद्ध राजस्थानी शिल्प। तांबे और कोबाल्ट के खनिज रंगों से बनाई गई फिरोजी चमक।",
        "photo_url": "https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?auto=format&fit=crop&w=900&q=80",
        "fields": {
            "craft": "pottery",
            "sub_craft": "blue-pottery",
            "material": "Crushed Quartz Stone, Glass, Multani Mitti, Gum",
            "material_cost_inr": 480,
            "material_source": "Jaipur Blue Pottery Crafts Guild",
            "technique": "Mold Pressing, Freehand Oxide Brush Painting, Low-Fire Glaze",
            "hours": 11,
            "wage_inr_per_hour": 90,
            "effort": "skilled",
            "gi": "yes",
            "motif": "Persian Arabesque & Peacock Plume",
            "colour": ["Turquoise Blue", "Ultramarine Cobalt", "Warm Amber"],
            "dimensions": "10 inch Diameter x 1.2 inch Depth",
            "weight_g": 720,
            "care_instructions": "Wipe with damp cloth. Decorative use only; not microwave or dishwasher safe.",
            "authenticity_mark": "Jaipur Blue Pottery GI Tagged",
        },
        "price_hint": 2200,
        "tags": [
            "pottery",
            "blue-pottery",
            "jaipur",
            "decorative-plate",
            "quartz",
            "rajasthan",
            "gi-tag",
            "wall-decor",
        ],
    },
    {
        "id": "longpi-black-stone-pottery-teapot",
        "category": "Pottery & Ceramics",
        "craft": "pottery",
        "cluster": "longpi",
        "cluster_name": "Longpi, Ukhrul, Manipur",
        "artisan": {
            "name": "Wungnaoshang Shimray",
            "phone": "+919862012313",
            "uid": "artisan-shimray-manipur",
            "experience_years": 32,
            "pehchan_id": "MN-UKH-LON-0312",
        },
        "title": "Longpi Manipuri Black Stone Handcrafted Teapot",
        "title_en": "Wheel-Less Serpentine Stone & Clay Teapot with Hand-Woven Cane Handle",
        "title_hi": "मणिपुरी लोंगपी काली पत्थर केतली - बेंत का हैंडल",
        "description": "Crafted without a potter's wheel by the Tangkhul Naga tribe in Manipur, using a balanced blend of serpentine rock and weathered black clay, polished to a metallic sheen with wild Machi leaves.",
        "desc_en": "Completely natural non-toxic earthenware with cane-wrapped insulating handle. Direct flame safe on gas stoves, infusing tea and broths with wholesome trace minerals.",
        "desc_hi": "मणिपुर के तांगखुल नागा आदिवासियों द्वारा बिना चाक के हाथों से बनाई गई प्राचीन केतली। सर्पेन्टाइन पत्थर और काली मिट्टी को माची के पत्तों से घिसकर दी गई प्राकृतिक चमक।",
        "photo_url": "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=900&q=80",
        "fields": {
            "craft": "pottery",
            "sub_craft": "stone-pottery",
            "material": "Serpentine Stone, Weathered Clay, Wild Hill Cane",
            "material_cost_inr": 620,
            "material_source": "Longpi Khullen Mountain Quarries",
            "technique": "Hand Modeling, Slap Technique, Open Bonfire Firing",
            "hours": 14,
            "wage_inr_per_hour": 85,
            "effort": "skilled",
            "gi": "yes",
            "motif": "Minimalist Naga Tribal Silhouette",
            "colour": ["Matte Charcoal Black", "Natural Cane Honey"],
            "dimensions": "850ml Capacity, 6.5 inch Height",
            "weight_g": 980,
            "care_instructions": "Stovetop safe. Clean with warm water and soft coir; no soap needed.",
            "authenticity_mark": "Manipuri Longpi GI Certified",
        },
        "price_hint": 2700,
        "tags": [
            "pottery",
            "longpi",
            "black-pottery",
            "manipur",
            "stone-pottery",
            "eco-friendly",
            "teapot",
            "cane",
        ],
    },
    {
        "id": "gorakhpur-terracotta-carved-horse",
        "category": "Pottery & Ceramics",
        "craft": "pottery",
        "cluster": "gorakhpur",
        "cluster_name": "Gorakhpur, Uttar Pradesh",
        "artisan": {
            "name": "Dinanath Prajapati",
            "phone": "+919451023414",
            "uid": "artisan-dinanath-gorakhpur",
            "experience_years": 27,
            "pehchan_id": "UP-GOR-TER-6671",
        },
        "title": "Gorakhpur Terracotta Traditional War Horse",
        "title_en": "Handcrafted Clay Horse Figurine with Filigree Neck Embellishments",
        "title_hi": "गोरखपुर टेराकोटा पारंपरिक सजीला घोड़ा - लाल मिट्टी शिल्प",
        "description": "Originating in the forested villages of Aurangabad in Gorakhpur, this traditional terracotta horse is assembled from individually wheel-thrown cylinders and detailed with delicate clay filigree bells and bridle.",
        "desc_en": "Created using alluvial silt dug from local riverbanks, coated with a natural red slip (Kabis) prepared from yellow clay and mango bark water, wood-fired in rustic underground kilns.",
        "desc_hi": "गोरखपुर के औरंगाबाद गांव की पुश्तैनी मिट्टी कला। चाक पर अलग-अलग अंगों को बनाकर जोड़ना और उस पर कच्ची मिट्टी की घंटियां व आभूषण उकेरना। प्राकृतिक कबीस की सुर्ख लाल रंगत।",
        "photo_url": "https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=900&q=80",
        "fields": {
            "craft": "pottery",
            "sub_craft": "terracotta",
            "material": "Local Alluvial River Clay, Mango Bark Extract, Natural Kabis",
            "material_cost_inr": 290,
            "material_source": "Rapti River Canal Beds Gorakhpur",
            "technique": "Wheel Component Throwing, Hand Clay Applique, Pit Kiln",
            "hours": 10,
            "wage_inr_per_hour": 80,
            "effort": "normal",
            "gi": "yes",
            "motif": "Ashwa (War Horse) with Jhumka Garland",
            "colour": ["Earthy Terracotta Red", "Burnt Saffron"],
            "dimensions": "12 inch Height x 9 inch Length x 4 inch Width",
            "weight_g": 1350,
            "care_instructions": "Dust gently with dry brush. Keep away from prolonged standing water.",
            "authenticity_mark": "Gorakhpur Terracotta GI Tagged",
        },
        "price_hint": 1650,
        "tags": [
            "pottery",
            "terracotta",
            "gorakhpur",
            "figurine",
            "horse",
            "folk-art",
            "gi-tag",
            "rustic",
        ],
    },
    {
        "id": "nizamabad-black-pottery-surahi",
        "category": "Pottery & Ceramics",
        "craft": "pottery",
        "cluster": "nizamabad",
        "cluster_name": "Nizamabad, Azamgarh, Uttar Pradesh",
        "artisan": {
            "name": "Shamim Akhtar",
            "phone": "+919450098715",
            "uid": "artisan-shamim-nizamabad",
            "experience_years": 35,
            "pehchan_id": "UP-AZA-NIZ-2021",
        },
        "title": "Nizamabad Mirrored Silver Inlaid Black Clay Surahi",
        "title_en": "Smoke-Fired Lustrous Black Clay Flask with Zinc-Silver Engraved Foil",
        "title_hi": "निजामाबाद काली मिट्टी सुराही - चांदी जैसी नक्काशी",
        "description": "Distinguished by its midnight black body achieved by sealing the kiln with mustard oil cakes to trap dense carbon smoke, this historic pitcher features intricate incised lines filled with glittering silvery amalgam.",
        "desc_en": "Throw-shuttle shaped pitcher rubbed with mountain clay slip and river pebble polished before smoke reduction firing. The incised grooves are manually filled with silvery metal foil (lead-free zinc alloy).",
        "desc_hi": "सरसों की खली के धुएं में बंद भट्ठी में पकाई जाने वाली चमकदार काली सुराही। बारीक खुदी हुई लकीरों में चांदी जैसी चमक भरने की दुर्लभ आज़मगढ़ी कला।",
        "photo_url": "https://images.unsplash.com/photo-1590483736622-39da86788790?auto=format&fit=crop&w=900&q=80",
        "fields": {
            "craft": "pottery",
            "sub_craft": "black-pottery",
            "material": "Clay, Mustard Seed Oil, Pewter/Zinc Metal Foil Filling",
            "material_cost_inr": 480,
            "material_source": "Azamgarh Clay Cooperatives",
            "technique": "Reduction Smoke Firing, Pebble Polishing, Zarkasi Inlay",
            "hours": 13,
            "wage_inr_per_hour": 80,
            "effort": "skilled",
            "gi": "yes",
            "motif": "Floral Jharokha & Diagonal Chevron",
            "colour": ["Jet Obsidian Black", "Glittering Silver"],
            "dimensions": "10.5 inch Height x 5.5 inch Diameter (1.2L)",
            "weight_g": 890,
            "care_instructions": "Dust with dry soft cloth. Keep dry to protect silvery inlay.",
            "authenticity_mark": "Nizamabad Black Clay GI Certified",
        },
        "price_hint": 2150,
        "tags": [
            "pottery",
            "nizamabad",
            "black-clay",
            "surahi",
            "silver-engraved",
            "azamgarh",
            "gi-tag",
        ],
    },

    # -------------------------------------------------------------------------
    # 4. Woodcraft & Lacquerware (5 items)
    # -------------------------------------------------------------------------
    {
        "id": "saharanpur-carved-sheesham-box",
        "category": "Woodcraft & Lacquerware",
        "craft": "woodcraft",
        "cluster": "saharanpur",
        "cluster_name": "Saharanpur, Uttar Pradesh",
        "artisan": {
            "name": "Master Irfan Ansari",
            "phone": "+919837234516",
            "uid": "artisan-irfan-saharanpur",
            "experience_years": 31,
            "pehchan_id": "UP-SAH-WOO-7719",
        },
        "title": "Saharanpur Hand-Carved Sheesham Jali Jewelry Box",
        "title_en": "Seasoned Indian Rosewood Keepsake Box with Brass Floral Inlay & Jali Cutwork",
        "title_hi": "सहारनपुर नक्काशीदार शीशम लकड़ी बॉक्स - जाली व पीतल का काम",
        "description": "Crafted from legally sourced seasoned Dalbergia sissoo (Sheesham wood), this heirloom jewelry chest features pierced openwork floral Jali patterns hand-chiseled through the lid, complemented by inlaid brass wire.",
        "desc_en": "Finished with natural bee-wax polish highlighting the deep dual-tone grain of rosewood. Velvet lined interior with removable compartmentalized tray and brass antique latch.",
        "desc_hi": "सहारनपुर की विश्वप्रसिद्ध काष्ठकला। पक्के शीशम की लकड़ी पर हाथ से काटी गई बारीक जाली और ढक्कन पर पीतल के तारों की जड़ाई। प्राकृतिक मोम की सुरक्षित पॉलिश।",
        "photo_url": "https://images.unsplash.com/photo-1532372576444-dda954194ad0?auto=format&fit=crop&w=900&q=80",
        "fields": {
            "craft": "woodcraft",
            "sub_craft": "carving",
            "material": "Aged Sheesham Wood (Indian Rosewood), Brass Wire, Velvet",
            "material_cost_inr": 720,
            "material_source": "Saharanpur Timber Forest Corporation",
            "technique": "Fretwork Jali Cutting, Tarkashi Brass Inlay, Hand Beeswax",
            "hours": 15,
            "wage_inr_per_hour": 95,
            "effort": "skilled",
            "gi": "yes",
            "motif": "Floral Mughal Jali & Foliage Vine",
            "colour": ["Warm Chestnut", "Golden Brass"],
            "dimensions": "8 inch Length x 5 inch Width x 3.5 inch Height",
            "weight_g": 920,
            "care_instructions": "Wipe with dry microfiber cloth. Polish with drop of linseed or walnut oil.",
            "authenticity_mark": "Saharanpur Woodcraft GI Tagged",
        },
        "price_hint": 2950,
        "tags": [
            "woodcraft",
            "sheesham",
            "saharanpur",
            "jali-carving",
            "jewelry-box",
            "gi-tag",
            "keepsake",
            "timber",
        ],
    },
    {
        "id": "channapatna-wooden-toy-train",
        "category": "Woodcraft & Lacquerware",
        "craft": "woodcraft",
        "cluster": "channapatna",
        "cluster_name": "Channapatna, Ramanagara, Karnataka",
        "artisan": {
            "name": "Naveen Gowda",
            "phone": "+919845012317",
            "uid": "artisan-gowda-channapatna",
            "experience_years": 19,
            "pehchan_id": "KA-RAM-CHA-3012",
        },
        "title": "Channapatna Organic Lacquer Wooden Toy Train",
        "title_en": "Child-Safe Turned Wood Engine & Bogie Set Colored with Turmeric & Indigo Lac",
        "title_hi": "चन्नापट्टना प्राकृतिक लाख लकड़ी रेलगाड़ी - बाल-सुरक्षित खिलौना",
        "description": "Known as the Gombegala Ooru (Toy Town), Channapatna craftsmen turn soft Ivory Wood (Wrightia tinctoria) on high-speed lathes and polish with non-toxic lac dyed with turmeric, indigo, and katha tree extracts.",
        "desc_en": "100% child-safe, organic wooden toy featuring rounded edge engine and two detachable magnetic coupling carriages. Friction heating against dried palm leaves bonds the brilliant organic gloss.",
        "desc_hi": "कर्नाटक के खिलौना नगर की ३०० वर्ष पुरानी परंपरा। 'आले मारा' लकड़ी को खराद पर घुमाकर हल्दी और नील से बने प्राकृतिक लाख से रंगा गया। पूरी तरह सुरक्षित व विषमुक्त।",
        "photo_url": "https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?auto=format&fit=crop&w=900&q=80",
        "fields": {
            "craft": "woodcraft",
            "sub_craft": "lacquerware",
            "material": "Aale Mara (Ivory Wood / Wrightia tinctoria), Natural Shellac",
            "material_cost_inr": 380,
            "material_source": "Karnataka Forest Industries Corporation",
            "technique": "Lathe Wood Turning & Natural Friction Lac Polishing",
            "hours": 8,
            "wage_inr_per_hour": 85,
            "effort": "normal",
            "gi": "yes",
            "motif": "Traditional Spherical Geometric Turning",
            "colour": ["Sun Yellow", "Vermilion Red", "Forest Green", "Ivory"],
            "dimensions": "14 inch Total Length x 3.2 inch Height",
            "weight_g": 410,
            "care_instructions": "Wipe with slightly damp cloth. Avoid soaking in water.",
            "authenticity_mark": "Channapatna Toys GI Certified",
        },
        "price_hint": 1400,
        "tags": [
            "woodcraft",
            "channapatna",
            "lacquerware",
            "toys",
            "non-toxic",
            "karnataka",
            "gi-tag",
            "kids",
        ],
    },
    {
        "id": "kashmir-walnut-wood-carved-panel",
        "category": "Woodcraft & Lacquerware",
        "craft": "woodcraft",
        "cluster": "kashmir",
        "cluster_name": "Srinagar, Jammu & Kashmir",
        "artisan": {
            "name": "Farooq Ahmad Bhat",
            "phone": "+919419123418",
            "uid": "artisan-farooq-kashmir",
            "experience_years": 38,
            "pehchan_id": "JK-SRI-WAL-0082",
        },
        "title": "Kashmiri Carved Walnut Wood Wall Art Panel",
        "title_en": "Masterpiece Deep Relief Walnut Wood Panel with Grapevine & Lotus Motifs",
        "title_hi": "कश्मीरी अखरोट की लकड़ी पर नक्काशीदार वॉल पैनल",
        "description": "Carved from mature root wood of high-altitude Kashmiri walnut trees (Juglans regia) cured underground for two years, this panel displays breathtaking three-dimensional undercut relief carving.",
        "desc_en": "Executed without artificial stains or lacquers; the natural grey-brown tones of the walnut grain are buffed to a silk finish using raw agate stones and pure walnut seed oil.",
        "desc_hi": "श्रीनगर के उस्तादों द्वारा पक्के अखरोट की जड़ की लकड़ी पर त्रि-आयामी (3D) नक्काशी। अंगूर की बेलें और कमल के फूल इतने गहरे तराशे गए हैं कि वे जीवित प्रतीत होते हैं।",
        "photo_url": "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=900&q=80",
        "fields": {
            "craft": "woodcraft",
            "sub_craft": "walnut",
            "material": "High-Altitude Seasoned Kashmir Walnut Wood (Root Grain)",
            "material_cost_inr": 2400,
            "material_source": "Kashmir Walnut Wood Cooperative",
            "technique": "Sunken Deep Relief Chisel Carving (Jaldar) & Agate Polishing",
            "hours": 34,
            "wage_inr_per_hour": 110,
            "effort": "skilled",
            "gi": "yes",
            "motif": "Angoor Vine (Grapevine) & Pamposh Lotus",
            "colour": ["Smoky Walnut Brown", "Deep Espresso Grain"],
            "dimensions": "18 inch Height x 12 inch Width x 1.5 inch Solid Thickness",
            "weight_g": 2100,
            "care_instructions": "Dust with camel-hair brush. Rub with pure walnut oil twice a year.",
            "authenticity_mark": "Kashmir Walnut Wood Carving GI Certified",
        },
        "price_hint": 8600,
        "tags": [
            "woodcraft",
            "walnut-wood",
            "kashmir",
            "wall-decor",
            "hand-carved",
            "heritage",
            "gi-tag",
            "luxury",
        ],
    },
    {
        "id": "kondapalli-dhasavatharam-wooden-dolls",
        "category": "Woodcraft & Lacquerware",
        "craft": "woodcraft",
        "cluster": "kondapalli",
        "cluster_name": "Kondapalli, Krishna, Andhra Pradesh",
        "artisan": {
            "name": "K. Satyanarayana",
            "phone": "+919848123419",
            "uid": "artisan-satya-kondapalli",
            "experience_years": 27,
            "pehchan_id": "AP-KRI-KON-5511",
        },
        "title": "Kondapalli Traditional Dasavatharam Doll Set",
        "title_en": "Hand-Carved Softwood 10 Avatars of Vishnu Figurine Heritage Set",
        "title_hi": "कोंडापल्ली दशावतार लकड़ी खिलौना सेट - प्राकृतिक लोक कला",
        "description": "Originating over 400 years ago in Andhra Pradesh, these sacred icons are carved out of locally sourced Tella Poniki softwood, joined with tamarind seed gum, and hand-painted with fine squirrel hair brushes.",
        "desc_en": "Set of 10 mythological figurines representing the Dashavatara of Lord Vishnu. Each avatar is distinguished by classical iconographic weapons, postures, and vibrant non-toxic mineral colors.",
        "desc_hi": "आंध्र प्रदेश की ४०० वर्ष पुरानी पुश्तैनी कला। 'तेल्ला पोनिकी' हल्की लकड़ी को तराशकर इमली के बीजों के गोंद से जोड़ना और गिलहरी के बालों के ब्रश से चेहरे की भाव-भंगिमाएं बनाना।",
        "photo_url": "https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=900&q=80",
        "fields": {
            "craft": "woodcraft",
            "sub_craft": "toys",
            "material": "Tella Poniki Softwood, Tamarind Seed Paste, Natural Pigments",
            "material_cost_inr": 680,
            "material_source": "Kondapalli Hill Forest Gatherers",
            "technique": "Hand Whittling, Sawdust Adhesive Joining, Fine Brush Work",
            "hours": 18,
            "wage_inr_per_hour": 85,
            "effort": "skilled",
            "gi": "yes",
            "motif": "Dashavatara Mythological Iconography",
            "colour": ["Sacred Ochre", "Temple Red", "Cobalt Sky Blue", "Gold Leaf"],
            "dimensions": "5.5 inch Height each (Set of 10 pieces with wooden stand)",
            "weight_g": 650,
            "care_instructions": "Keep in showcase or glass cabinet. Dust dry only.",
            "authenticity_mark": "Kondapalli Bommalu GI Certified",
        },
        "price_hint": 3200,
        "tags": [
            "woodcraft",
            "kondapalli",
            "dolls",
            "andhra-pradesh",
            "mythological",
            "gi-tag",
            "folk-art",
            "collectibles",
        ],
    },
    {
        "id": "sankheda-teak-wood-lacquered-chair",
        "category": "Woodcraft & Lacquerware",
        "craft": "woodcraft",
        "cluster": "sankheda",
        "cluster_name": "Sankheda, Chhota Udaipur, Gujarat",
        "artisan": {
            "name": "Kantilal Kharadi",
            "phone": "+919426012320",
            "uid": "artisan-kharadi-sankheda",
            "experience_years": 33,
            "pehchan_id": "GJ-CHO-SAN-1204",
        },
        "title": "Sankheda Hand-Lacquered Teak Accent Chair",
        "title_en": "Turned Teakwood Low Chair with Traditional Maroon Gold Tin-Foil Lacquer",
        "title_hi": "संखेड़ा हस्तनिर्मित सागवान लाख की कुर्सी - गुजराती परंपरा",
        "description": "A trademark of Gujarati wedding Mandaps and royal lounges, Sankheda furniture uses turned teakwood, painted by hand with tin foil paste that glows like burnished gold under tinted natural shellac coatings.",
        "desc_en": "Ergonomic low-seating armchair featuring hand-woven cotton-jute seat tape and turned balusters. The luminous golden floral scrolls are polished using smooth agate stones.",
        "desc_hi": "गुजरात की प्रसिद्ध संखेड़ा काष्ठकला। सागवान की मजबूत लकड़ी पर रांगे (टिन) के घोल से फूल-पत्तियां बनाकर उस पर पारदर्शी लाख की परत चढ़ाई जाती है, जिससे सुनहरी चमक आती है।",
        "photo_url": "https://images.unsplash.com/photo-1580481077195-c3a8864f7772?auto=format&fit=crop&w=900&q=80",
        "fields": {
            "craft": "woodcraft",
            "sub_craft": "furniture",
            "material": "Treated Teakwood (Sagwan), Shellac, Tin Paste, Cotton Cord",
            "material_cost_inr": 2900,
            "material_source": "Gujarat Forest Timber Depot",
            "technique": "Lathe Spindle Turning, Tin Foil Hand Painting, Shellac Coat",
            "hours": 26,
            "wage_inr_per_hour": 90,
            "effort": "skilled",
            "gi": "yes",
            "motif": "Kalash, Peacock & Paisley Vines",
            "colour": ["Royal Maroon", "Metallic Gold", "Amber Honey"],
            "dimensions": "32 inch Height x 22 inch Width x 20 inch Seat Depth",
            "weight_g": 6200,
            "care_instructions": "Dust with dry cotton cloth. Do not expose to direct monsoon rain.",
            "authenticity_mark": "Sankheda Furniture GI Tagged",
        },
        "price_hint": 7800,
        "tags": [
            "woodcraft",
            "sankheda",
            "furniture",
            "gujarat",
            "lacquerware",
            "gi-tag",
            "chair",
            "heritage",
        ],
    },

    # -------------------------------------------------------------------------
    # 5. Leather & Footwear (5 items)
    # -------------------------------------------------------------------------
    {
        "id": "kolhapuri-handbraided-leather-chappal",
        "category": "Leather & Footwear",
        "craft": "leathercraft",
        "cluster": "kolhapur",
        "cluster_name": "Kolhapur, Maharashtra",
        "artisan": {
            "name": "Santosh Shinde",
            "phone": "+919822123421",
            "uid": "artisan-shinde-kolhapur",
            "experience_years": 25,
            "pehchan_id": "MH-KOL-LEA-8812",
        },
        "title": "Kolhapuri Hand-Braided Authentic Leather Chappal",
        "title_en": "Pure Vegetable-Tanned Leather Chappal with Intricate Hand-Braided Strap",
        "title_hi": "कोल्हापुरी हाथ से गुंथी शुद्ध चमड़ा चप्पल - बागेरी काम",
        "description": "Crafted from 100% natural vegetable-tanned buffalo and cow hide cured with babul bark and harda fruit extracts in pit vats, hand-stitched entirely with leather thongs without a single iron nail.",
        "desc_en": "Known for its distinctive squeak and lifetime longevity, softening to mold around the wearer's foot bed. Features intricate plaiting (Bageri cord) and punched openwork punch medallions.",
        "desc_hi": "बिना किसी लोहे की कील के, शुद्ध चमड़े के धागों से सिली गई विश्वप्रसिद्ध कोल्हापुरी चप्पल। बबूल की छाल से पकाया गया प्राकृतिक चमड़ा जो पैरों को ठंडक प्रदान करता है।",
        "photo_url": "https://images.unsplash.com/photo-1603808033192-082d6919d3e1?auto=format&fit=crop&w=900&q=80",
        "fields": {
            "craft": "leathercraft",
            "sub_craft": "chappal",
            "material": "Vegetable-Tanned Buffalo & Cow Hide, Babul Bark, Castor Oil",
            "material_cost_inr": 850,
            "material_source": "Kolhapur Tanners Leather Cooperative",
            "technique": "Hand Skiving, Leather Thong Stitching, Vegetable Bark Tanning",
            "hours": 12,
            "wage_inr_per_hour": 90,
            "effort": "skilled",
            "gi": "yes",
            "motif": "Traditional Bageri Cord & Punya Medallion",
            "colour": ["Natural Tan", "Mahogany Cognac"],
            "dimensions": "Available in UK/India Sizes 6 to 11",
            "weight_g": 520,
            "care_instructions": "Season with a few drops of mustard oil before first wear. Avoid wet puddles.",
            "authenticity_mark": "Kolhapuri Chappals GI Certified",
        },
        "price_hint": 2600,
        "tags": [
            "leathercraft",
            "kolhapuri",
            "chappal",
            "footwear",
            "vegetable-tanned",
            "maharashtra",
            "gi-tag",
            "hand-stitched",
        ],
    },
    {
        "id": "jodhpur-embroidered-velvet-mojari",
        "category": "Leather & Footwear",
        "craft": "leathercraft",
        "cluster": "jodhpur",
        "cluster_name": "Jodhpur, Rajasthan",
        "artisan": {
            "name": "Bhanwar Lal Regar",
            "phone": "+919829123422",
            "uid": "artisan-bhanwar-jodhpur",
            "experience_years": 28,
            "pehchan_id": "RJ-JOD-MOJ-3301",
        },
        "title": "Jodhpur Royal Velvet Zari Embroidered Mojari",
        "title_en": "Curved-Toe Royal Rajasthani Mojari with Gold Zardozi Needlework",
        "title_hi": "जोधपुरी शाही मखमली जरी मोजड़ी - राजस्थानी जूती",
        "description": "Worn by erstwhile Rajput royalty, this comfortable ceremonial slip-on footwear features a curved pointed toe (Nokdar Muthia), soft velvet upper lavishly embroidered with golden bullion thread, and flexible camel leather soles.",
        "desc_en": "Double-stitched by hand with waxed cotton cords. Cushioned inner lining ensures comfort during weddings, festivals, and royal celebratory events.",
        "desc_hi": "शाही राजस्थानी परंपरा की नोकदार मोजड़ी। मुलायम मखमली कपड़े पर सोने की जरी और सलमे-सितारे का बारीक काम। लचीला चमड़े का तला जो पैरों में छाले नहीं पड़ने देता।",
        "photo_url": "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=900&q=80",
        "fields": {
            "craft": "leathercraft",
            "sub_craft": "mojari",
            "material": "Tanned Leather Sole, Silk Velvet Upper, Copper Zari Thread",
            "material_cost_inr": 820,
            "material_source": "Jodhpur Regar Mochiyan Market",
            "technique": "Hand Lasting, Nok Shaping, Zardozi Embroidery",
            "hours": 14,
            "wage_inr_per_hour": 85,
            "effort": "skilled",
            "gi": "no",
            "motif": "Royal Paisley & Rising Sun (Surya)",
            "colour": ["Midnight Navy", "Antique Gold Zari"],
            "dimensions": "Available in UK/India Sizes 7 to 11",
            "weight_g": 480,
            "care_instructions": "Dry brush to clean velvet. Store with shoe tree wrapped in paper.",
            "authenticity_mark": "Rajasthan Heritage Footwear Guild Verified",
        },
        "price_hint": 2850,
        "tags": [
            "leathercraft",
            "mojari",
            "jooti",
            "jodhpur",
            "rajasthan",
            "zari",
            "wedding-footwear",
            "velvet",
        ],
    },
    {
        "id": "shantiniketan-embossed-leather-tote",
        "category": "Leather & Footwear",
        "craft": "leathercraft",
        "cluster": "shantiniketan",
        "cluster_name": "Shantiniketan, Birbhum, West Bengal",
        "artisan": {
            "name": "Gouranga Das",
            "phone": "+919434012323",
            "uid": "artisan-gouranga-bengal",
            "experience_years": 21,
            "pehchan_id": "WB-BIR-SHA-9102",
        },
        "title": "Shantiniketan Hand-Embossed Batik Leather Tote",
        "title_en": "Batik-Dyed Grain Leather Shoulder Tote with Traditional Rural Folk Embossing",
        "title_hi": "शांतिनिकेतन बाटिक लेदर टोट बैग - हाथ से उभरी लोक कला",
        "description": "Pioneered under the aesthetic renaissance of Rabindranath Tagore's Visva-Bharati, this tote is made of vegetable-tanned goat grain leather, hand-embossed using hot steel metal plates and layered with translucent batik spirit dyes.",
        "desc_en": "Features dual leather shoulder straps, brass zippered secure compartments, and cotton drill interior lining. The rich amber-brown batik tones grow more lustrous with every year of use.",
        "desc_hi": "रवींद्रनाथ टैगोर के शांतिनिकेतन द्वारा पुनर्जीवित चमड़ा शिल्प। गर्म डाई की मदद से उभारी गई पारंपरिक बंगाली अल्पना और ग्रामीण जीवन की झलक। प्राकृतिक बाटिक रंगों की चमक।",
        "photo_url": "https://images.unsplash.com/photo-1590874103328-eac38a683ce7?auto=format&fit=crop&w=900&q=80",
        "fields": {
            "craft": "leathercraft",
            "sub_craft": "bags",
            "material": "Vegetable-Tanned Goat Grain Leather, Natural Spirit Dyes",
            "material_cost_inr": 1150,
            "material_source": "Shantiniketan Leather Cooperative",
            "technique": "Hand Embossing, Touch-Batik Dye Layering, Saddle Stitching",
            "hours": 16,
            "wage_inr_per_hour": 85,
            "effort": "skilled",
            "gi": "yes",
            "motif": "Alpana Floral Scrolls & Village Musicians",
            "colour": ["Cognac Amber", "Deep Terracotta", "Olive Undertones"],
            "dimensions": "15 inch Width x 12 inch Height x 4.5 inch Base",
            "weight_g": 680,
            "care_instructions": "Wipe with slightly moist cloth. Condition with neutral leather balm.",
            "authenticity_mark": "Shantiniketan Leather Goods GI Certified",
        },
        "price_hint": 3400,
        "tags": [
            "leathercraft",
            "shantiniketan",
            "batik-leather",
            "tote-bag",
            "west-bengal",
            "gi-tag",
            "fashion",
            "sustainable",
        ],
    },
    {
        "id": "bikaner-camel-leather-embossed-journal",
        "category": "Leather & Footwear",
        "craft": "leathercraft",
        "cluster": "bikaner",
        "cluster_name": "Bikaner, Rajasthan",
        "artisan": {
            "name": "Mohan Lal Usta",
            "phone": "+919414012324",
            "uid": "artisan-usta-bikaner",
            "experience_years": 24,
            "pehchan_id": "RJ-BIK-UST-1044",
        },
        "title": "Bikaner Camel Leather Embossed Heritage Journal",
        "title_en": "Handmade Deckle-Edge Cotton Paper Diary Bound in Tooled Camel Hide",
        "title_hi": "बीकानेर ऊंट के चमड़े की हस्तनिर्मित डायरी - प्राचीन कागज़",
        "description": "Covered in sturdy, naturally shed desert camel leather cured using mustard oil and sea salt, this heirloom journal contains 200 pages of handmade recycled cotton-rag deckle-edge paper bound with leather thongs.",
        "desc_en": "Features heat-embossed geometric mandalas and lockable wrap-around leather tie with an antique brass key charm. Fountain pen friendly paper that does not bleed.",
        "desc_hi": "रेगिस्तानी ऊंट के चमड़े पर गर्म ठप्पा लगाकर बनाई गई प्राचीन डायरी। इसमें २०० पन्नों का हाथ से बना सूती कागज़ है, जिस पर स्याही फैलती नहीं है।",
        "photo_url": "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=900&q=80",
        "fields": {
            "craft": "leathercraft",
            "sub_craft": "stationery",
            "material": "Tanned Camel Hide, Handmade Cotton Rag Paper, Brass Key",
            "material_cost_inr": 490,
            "material_source": "Bikaner Camel Breeders Association",
            "technique": "Coptic Hand Binding, Leather Blind Tooling, Bark Tanning",
            "hours": 9,
            "wage_inr_per_hour": 85,
            "effort": "normal",
            "gi": "no",
            "motif": "Thar Desert Sun Mandala & Geometric Borders",
            "colour": ["Distressed Saddle Brown", "Antique Brass"],
            "dimensions": "8.5 inch x 6.0 inch x 1.5 inch (200 Unlined Pages)",
            "weight_g": 540,
            "care_instructions": "Store in dry place. Leather will develop rich patina with touch.",
            "authenticity_mark": "Bikaner Usta Heritage Guild Certified",
        },
        "price_hint": 1750,
        "tags": [
            "leathercraft",
            "camel-leather",
            "journal",
            "bikaner",
            "handmade-paper",
            "stationery",
            "vintage",
        ],
    },
    {
        "id": "kanpur-fullgrain-leather-weekender-bag",
        "category": "Leather & Footwear",
        "craft": "leathercraft",
        "cluster": "kanpur",
        "cluster_name": "Kanpur, Uttar Pradesh",
        "artisan": {
            "name": "Ashok Verma",
            "phone": "+919839012325",
            "uid": "artisan-ashok-kanpur",
            "experience_years": 30,
            "pehchan_id": "UP-KAN-LEA-7789",
        },
        "title": "Kanpur Full-Grain Saddlery Leather Duffle",
        "title_en": "Handcrafted Heavy-Duty Weekender Travel Bag with Solid Cast Brass Fittings",
        "title_hi": "कानपुर फुल-ग्रेन लेदर वीकेंडर डफल बैग - शुद्ध चमड़ा",
        "description": "Crafted in India's historic leather capital using 2.2mm thick pull-up full-grain leather from ethical dairies, stitched with heavy waxed bonded nylon threads, and equipped with rugged solid brass hardware.",
        "desc_en": "Reinforced base with metal studs, detachable padded shoulder sling, inner laptop sleeve, and YKK double-pull brass zippers. Built to endure decades of global travel.",
        "desc_hi": "कानपुर के चर्म उद्योग की सर्वश्रेष्ठ पहचान। २.२ मिमी मोटा असली फुल-ग्रेन चमड़ा, जिसे हाथ से मोम धागे से सिला गया है। पीतल के मजबूत बकल और लाइफटाइम चलने वाली गुणवत्ता।",
        "photo_url": "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=900&q=80",
        "fields": {
            "craft": "leathercraft",
            "sub_craft": "luggage",
            "material": "Full-Grain Oil Pullup Cowhide Leather (2.2mm), Solid Brass",
            "material_cost_inr": 2800,
            "material_source": "Jajmau Kanpur Eco-Tannery Council",
            "technique": "Saddlery Bench Craft, Double Needle Saddle Stitch, Burnishing",
            "hours": 22,
            "wage_inr_per_hour": 95,
            "effort": "skilled",
            "gi": "no",
            "motif": "Classic Minimalist British Colonial Saddlery",
            "colour": ["Vintage Dark Tan", "Matte Antique Brass"],
            "dimensions": "21 inch Length x 11 inch Height x 10 inch Depth (42L)",
            "weight_g": 1950,
            "care_instructions": "Treat with natural beeswax conditioner annually. Avoid soaking.",
            "authenticity_mark": "Council for Leather Exports Certified",
        },
        "price_hint": 7200,
        "tags": [
            "leathercraft",
            "duffle-bag",
            "full-grain",
            "kanpur",
            "travel-bag",
            "heritage-leather",
            "luxury",
        ],
    },

    # -------------------------------------------------------------------------
    # 6. Stone Craft & Jewelry (5 items)
    # -------------------------------------------------------------------------
    {
        "id": "agra-pietra-dura-marble-inlay-coasters",
        "category": "Stone Craft & Jewelry",
        "craft": "stonecraft",
        "cluster": "agra",
        "cluster_name": "Agra, Uttar Pradesh",
        "artisan": {
            "name": "Arif Khan",
            "phone": "+919837098726",
            "uid": "artisan-arif-agra",
            "experience_years": 27,
            "pehchan_id": "UP-AGR-MAR-4501",
        },
        "title": "Agra Taj Mahal Marble Inlay Coaster Set",
        "title_en": "Makrana White Marble Parchin Kari Coasters Inlaid with Semi-Precious Gems",
        "title_hi": "आगरा पच्चीकारी संगमरमर कोस्टर सेट - अर्ध-कीमती रत्न जड़ाई",
        "description": "Continuing the exact Parchin Kari (Pietra Dura) lapidary art seen on the Taj Mahal, these coasters are carved out of non-porous Makrana marble and inlaid with hand-sliced Lapis Lazuli, Malachite, Jasper, and Carnelian.",
        "desc_en": "Set of 4 marble coasters with velvet-cushioned bases and a matching carved marble holder. Each flower petal is hand-ground on emery diamond wheels and tapped into chiseled stone cavities.",
        "desc_hi": "ताजमहल के कारीगरों के वंशज द्वारा मकराना के सफेद संगमरमर पर हस्तनिर्मित पच्चीकारी। लाजवर्द, मैलाकाइट और कार्नेलियन जैसे रत्नों को तराशकर पत्थर के अंदर जड़ा गया है।",
        "photo_url": "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=900&q=80",
        "fields": {
            "craft": "stonecraft",
            "sub_craft": "marble-inlay",
            "material": "Makrana White Marble, Lapis Lazuli, Malachite, Carnelian",
            "material_cost_inr": 1600,
            "material_source": "Agra Stone Artisans Guild",
            "technique": "Parchin Kari (Pietra Dura), Emery Wheel Gem Grinding",
            "hours": 20,
            "wage_inr_per_hour": 100,
            "effort": "skilled",
            "gi": "yes",
            "motif": "Taj Mahal 16-Petal Floral Bouquet",
            "colour": ["Pristine White", "Royal Lapis Blue", "Peacock Malachite"],
            "dimensions": "4 inch Diameter each (Set of 4 with round marble holder)",
            "weight_g": 980,
            "care_instructions": "Wipe with damp cloth and mild soap. Do not use harsh toilet/vinegar acids.",
            "authenticity_mark": "Agra Marble Inlay GI Certified",
        },
        "price_hint": 5100,
        "tags": [
            "stonecraft",
            "marble",
            "agra",
            "pietra-dura",
            "tableware",
            "coasters",
            "gi-tag",
            "taj-mahal",
        ],
    },
    {
        "id": "jaipur-kundan-meenakari-choker-necklace",
        "category": "Stone Craft & Jewelry",
        "craft": "jewelry",
        "cluster": "jaipur",
        "cluster_name": "Jaipur, Rajasthan",
        "artisan": {
            "name": "Govind Narain Soni",
            "phone": "+919829012327",
            "uid": "artisan-govind-jaipur",
            "experience_years": 36,
            "pehchan_id": "RJ-JAI-MEE-2201",
        },
        "title": "Jaipur Royal Kundan Meenakari Choker",
        "title_en": "Reversible 22K Gold Foil Kundan Choker with Reverse Enamel Meenakari Art",
        "title_hi": "जयपुर कुंदन मीनाकारी शाही चोकर हार - दोतरफा दस्तकारी",
        "description": "A magnificent example of Jaipur's twin royal crafts: the front features glass uncut gems set into 22K refined gold foil (Kundan Jadau), while the reverse exhibits breathtaking multi-color vitreous enamel (Meenakari).",
        "desc_en": "Adorned with cultured seed pearls and emerald-green drops, strung on an adjustable handmade silk Zari cord (Dori). Fully reversible to wear with both traditional and fusion attire.",
        "desc_hi": "जयपुर के जौहरी बाजार की विश्वप्रसिद्ध कला। सामने शुद्ध सोने की पत्ती (कुंदन) में जड़े अनकट नगीने और पीछे आग में पकाई गई बहुरंगी मीनाकारी। साथ में बंधे हुए प्राकृतिक मोती।",
        "photo_url": "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=900&q=80",
        "fields": {
            "craft": "jewelry",
            "sub_craft": "meenakari",
            "material": "Silver Base, 22K Gold Foil, Glass Enamel, Seed Pearls",
            "material_cost_inr": 3400,
            "material_source": "Jaipur Gem & Jewelry Bourse",
            "technique": "Jadau Kundan Setting, Champlevé Meenakari, Kiln Firing",
            "hours": 28,
            "wage_inr_per_hour": 100,
            "effort": "skilled",
            "gi": "yes",
            "motif": "Mughal Mayur (Peacock) & Floral Jharokha",
            "colour": ["Ruby Red", "Emerald Green", "Warm White", "22K Gold"],
            "dimensions": "Choker Width 2 inch, Length 8 inch + Adjustable Silk Dori",
            "weight_g": 140,
            "care_instructions": "Keep away from perfumes, hairsprays, and moisture. Store in cotton box.",
            "authenticity_mark": "Jaipur Meenakari & Kundan GI Certified",
        },
        "price_hint": 9500,
        "tags": [
            "jewelry",
            "kundan",
            "meenakari",
            "jaipur",
            "necklace",
            "bridal",
            "rajasthan",
            "gi-tag",
            "royal",
        ],
    },
    {
        "id": "cuttack-silver-filigree-peacock-brooch",
        "category": "Stone Craft & Jewelry",
        "craft": "jewelry",
        "cluster": "cuttack",
        "cluster_name": "Cuttack, Odisha",
        "artisan": {
            "name": "Pradip Kumar Sahoo",
            "phone": "+919437012328",
            "uid": "artisan-pradip-cuttack",
            "experience_years": 32,
            "pehchan_id": "OR-CUT-TAR-9011",
        },
        "title": "Cuttack Tarakasi Silver Filigree Peacock Brooch",
        "title_en": "92.5 Sterling Silver Hair-Thin Wire Filigree Brooch Pin of Dancing Peacock",
        "title_hi": "कटक तारकशी चांदी मयूर ब्रोच - सूक्ष्म चांदी के तार",
        "description": "Known as Tarakasi in Odisha for over five centuries, pure silver is drawn through steel dies into wires as thin as human hair, curled into micro-spirals, and soldered with charcoal blowpipes into a dancing peacock.",
        "desc_en": "Certified 92.5 Sterling Silver brooch pin with secure locking safety clasp. Light as lace yet structurally durable due to ancient annealing techniques.",
        "desc_hi": "ओडिशा की ५०० वर्ष पुरानी तारकशी कला। शुद्ध चांदी को इंसान के बाल से भी पतले तारों में खींचकर, चिमटी से घुमावदार जाली बनाकर कोयले की फूंकनी से जोड़ा गया मोर।",
        "photo_url": "https://images.unsplash.com/photo-1611591475152-4783113828af?auto=format&fit=crop&w=900&q=80",
        "fields": {
            "craft": "jewelry",
            "sub_craft": "filigree",
            "material": "92.5 Sterling Silver, Hair-Thin Drawn Silver Wires",
            "material_cost_inr": 1250,
            "material_source": "Cuttack Tarakasi Artisans Cooperative",
            "technique": "Hand Wire Drawing, Charcoal Block Blowpipe Soldering",
            "hours": 15,
            "wage_inr_per_hour": 95,
            "effort": "skilled",
            "gi": "yes",
            "motif": "Mayura (Dancing Peacock) in Full Plumage",
            "colour": ["Bright Sterling Silver White"],
            "dimensions": "3.0 inch Length x 2.2 inch Width",
            "weight_g": 38,
            "care_instructions": "Store in ziplock pouch with anti-tarnish strip. Clean with silver foam.",
            "authenticity_mark": "Cuttack Rupa Tarakasi GI Certified",
        },
        "price_hint": 3800,
        "tags": [
            "jewelry",
            "filigree",
            "tarakasi",
            "cuttack",
            "silver",
            "odisha",
            "peacock",
            "gi-tag",
            "brooch",
        ],
    },
    {
        "id": "puri-soapstone-carved-tree-of-life",
        "category": "Stone Craft & Jewelry",
        "craft": "stonecraft",
        "cluster": "puri",
        "cluster_name": "Puri, Odisha",
        "artisan": {
            "name": "Rabindra Maharana",
            "phone": "+919438012329",
            "uid": "artisan-rabindra-puri",
            "experience_years": 29,
            "pehchan_id": "OR-PUR-STO-3392",
        },
        "title": "Puri Soapstone Carved Tree of Life Lamp",
        "title_en": "Monolithic Grey Soapstone Tealight Lamp with Undercut Birds & Floral Perforations",
        "title_hi": "पुरी सोपस्टोन कल्पवृक्ष जालीदार लैंप - पत्थर नक्काशी",
        "description": "Chiseled from a single block of soft Konark-quarried soapstone (Khadipathara) by sculptors trained in the lineage of the Konark Sun Temple architects, this ambient luminary glows through hundreds of hand-drilled perforations.",
        "desc_en": "Features the Kalpavriksha (Tree of Life) with songbirds perched among entwined boughs. Hollowed out center fits a tealight or LED candle, casting romantic lace shadows across the room.",
        "desc_hi": "कोणार्क सूर्य मंदिर के शिल्पियों के वंशजों द्वारा तराशा गया सोपस्टोन लैंप। एक ही पत्थर को अंदर से खोखला करके बनाई गई कल्पवृक्ष और चिड़ियों की महीन नक्काशी।",
        "photo_url": "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=900&q=80",
        "fields": {
            "craft": "stonecraft",
            "sub_craft": "soapstone",
            "material": "Monolithic Khadipathara (Natural Grey-Green Soapstone)",
            "material_cost_inr": 750,
            "material_source": "Nilagiri Hills Stone Quarries Odisha",
            "technique": "Hollow Core Drilling, Manual Steel Chisel Jali Undercutting",
            "hours": 18,
            "wage_inr_per_hour": 95,
            "effort": "skilled",
            "gi": "yes",
            "motif": "Kalpavriksha (Tree of Life) & Singing Myna",
            "colour": ["Natural Olive Soapstone Grey", "Earthy Speckled Cream"],
            "dimensions": "7.5 inch Height x 4.5 inch Base Diameter",
            "weight_g": 1420,
            "care_instructions": "Wash with warm water and soft sponge. Heat and wax resistant.",
            "authenticity_mark": "Odisha Stone Carving GI Tagged",
        },
        "price_hint": 3400,
        "tags": [
            "stonecraft",
            "soapstone",
            "puri",
            "odisha",
            "temple-art",
            "lamp",
            "tree-of-life",
            "gi-tag",
            "lighting",
        ],
    },
    {
        "id": "varanasi-pink-meenakari-lotus-earrings",
        "category": "Stone Craft & Jewelry",
        "craft": "jewelry",
        "cluster": "varanasi",
        "cluster_name": "Varanasi, Uttar Pradesh",
        "artisan": {
            "name": "Kunj Bihari Singh",
            "phone": "+919839912330",
            "uid": "artisan-kunj-varanasi",
            "experience_years": 34,
            "pehchan_id": "UP-VAR-GUL-5509",
        },
        "title": "Varanasi Gulabi Meenakari Lotus Danglers",
        "title_en": "Pure Silver Pink Enamel Jhumka Earrings with Natural Freshwater Pearl Drops",
        "title_hi": "वाराणसी गुलाबी मीनाकारी कमल झुमकी - दुर्लभ बनारसी कला",
        "description": "Considered the rarest enamel art in India, Gulabi Meenakari was brought to Kashi by Persian masters during the Mughal reign. White opaque enamel is first fired onto silver, then overpainted with translucent pink rose floral brush strokes.",
        "desc_en": "Handcrafted in 99% pure silver with tiered blooming lotus petals and dangling basra pearls. Requires up to four distinct kiln firings to achieve the delicate pastel petal shading.",
        "desc_hi": "काशी की दुर्लभ और लुप्तप्राय 'गुलाबी मीनाकारी'। शुद्ध चांदी पर सफेद इनेमल चढ़ाकर उस पर गुलाबी गुलाब के फूलों की सूक्ष्म चित्रकारी की जाती है। नीचे बंधे हुए प्राकृतिक मोती।",
        "photo_url": "https://images.unsplash.com/photo-1630019852942-f89202989a59?auto=format&fit=crop&w=900&q=80",
        "fields": {
            "craft": "jewelry",
            "sub_craft": "gulabi-meenakari",
            "material": "Pure Silver (99%), Rose Mineral Enamel, Freshwater Pearls",
            "material_cost_inr": 1150,
            "material_source": "Gai Ghat Meenakari Mohalla Varanasi",
            "technique": "Silver Repoussé, Multi-Fire Gulabi Enameling, Pearl Stringing",
            "hours": 16,
            "wage_inr_per_hour": 90,
            "effort": "skilled",
            "gi": "yes",
            "motif": "Kashi Kamal (Pink Lotus) & Hanging Jhumka",
            "colour": ["Pastel Rose Pink", "Chalk White", "Glistening Silver"],
            "dimensions": "2.8 inch Length x 1.1 inch Bell Width",
            "weight_g": 32,
            "care_instructions": "Store individually in velvet pouch. Avoid contact with hair lacquers.",
            "authenticity_mark": "Varanasi Gulabi Meenakari GI Certified",
        },
        "price_hint": 3600,
        "tags": [
            "jewelry",
            "meenakari",
            "gulabi-meenakari",
            "varanasi",
            "earrings",
            "lotus",
            "gi-tag",
            "silver",
            "heritage",
        ],
    },
]


def build_catalog_item(raw: dict[str, Any], settings: Any = None) -> dict[str, Any]:
    """Hydrate raw catalog item with computed pricing and cryptographic HMAC signature."""
    settings = settings or get_settings()
    listing_id = raw["id"]
    uid = raw["artisan"]["uid"]
    cluster = raw.get("cluster", "varanasi")
    fields = raw.get("fields", {})
    price_hint = raw.get("price_hint")

    prices = compute_prices(fields, cluster=cluster, listed=price_hint)
    signed_at = "2026-09-13T12:00:00+00:00"

    signature = compute_listing_signature(
        listing_id=listing_id,
        uid=uid,
        fields=fields,
        prices=prices,
        signed_at=signed_at,
        secret=settings.listing_hmac_secret,
    )

    base = settings.public_base_url.rstrip("/")
    public_url = f"{base}/v/{listing_id}"
    qr_url = f"{base}/v1/listings/{listing_id}/media/qr.png"
    photo_url = raw["photo_url"]

    return {
        "id": listing_id,
        "artisanId": uid,
        "artisan": raw["artisan"],
        "category": raw["category"],
        "craft": raw["craft"],
        "cluster": cluster,
        "cluster_name": raw.get("cluster_name", cluster.title()),
        "title": raw["title"],
        "title_en": raw.get("title_en", raw["title"]),
        "title_hi": raw.get("title_hi", ""),
        "description": raw["description"],
        "desc_en": raw.get("desc_en", raw["description"]),
        "desc_hi": raw.get("desc_hi", ""),
        "photo_url": photo_url,
        "image_url": photo_url,
        "originalUrl": photo_url,
        "studioUrl": photo_url,
        "fields": fields,
        "prices": prices,
        "listed_price": prices["listed"]["value"],
        "price_hint": prices["listed"]["value"],
        "tags": raw.get("tags", []),
        "status": "published",
        "signature": signature,
        "signed_at": signed_at,
        "signedAt": signed_at,
        "public_url": public_url,
        "qr_url": qr_url,
        "source_label": "KalaSetu Verified",
        "createdAt": signed_at,
        "updatedAt": signed_at,
    }


def get_all_30_catalog_items(settings: Any = None) -> list[dict[str, Any]]:
    """Return all 30 hydrated, signed, and price-calculated catalog products."""
    return [build_catalog_item(item, settings=settings) for item in RAW_CATALOG_DATA]
